### ISSUE TITLE
localhost:50051 ???

### ISSUE THREAD

**Issue by rcemper** [jrpereirajr/iris-grpc-example#4]
?? what stands this for with docker.
What service is this. ?

irisowner@4b3e7a665485:/tmp$ ./grpcurl \
>     -plaintext  \
>     -d '{"name":"you"}' \
>     -import-path /irisrun/repo/jrpereira/python/grpc-test \
>     -proto helloworld.proto \
>     localhost:50051 \
>     helloworld.MultiGreeter.SayHello
Failed to dial target host "localhost:50051": dial tcp 127.0.0.1:50051: connect: connection refused

**Comment by jrpereirajr** [comment]
Hi!

Sorry for the late response.

The port 50051 is the gRPC port used by the gRPC server in this example.
Try to run these lines in another terminal before trying to use the `grpcurl` gRPC client:

```
Set server = ##class(dc.jrpereira.gRPC.HelloWorldServer).%New()
Do server.Start()
```

This will start the gRPC server and them you're able to use th `grpcurl` client.

Please, let me know if this works for you, so I'll improve the documentation.

Thanks,
José

**Comment by rcemper** [comment]
Thanks !  that worked.
It turned out that  grpcurl client was the problem.

**Comment by jrpereirajr** [comment]
I updated the `grpcurl` section with you input.
Thanks for the feedback.
